import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Calendar from 'react-calendar';
import { useState } from 'react';
import { Col, Container, Row, Text, Textarea } from '@nextui-org/react';

const Home: NextPage = () => {

  const [date, setDate] = useState(new Date())

  const [text, setText] = useState('')

  return (
    <div className={styles.container}>
      <Head>
        <title>NLP Mood Journal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Row justify='center'>
          <Text h1>NLP Mood Journal</Text>
        </Row>
        <Row justify='center'>
            <Calendar onChange={setDate} value={date} />
        </Row>
        <Row>
          <Text>Daily Journal for {date.toLocaleDateString()}</Text>
        </Row>
        <Row>
          <Textarea value={text} onChange={e => setText(e.target.value)}></Textarea>
        </Row>
      </Container>

      
    </div>
  )
}

export default Home
